spring.application.name=envio_ms
server.port=8091

spring.datasource.url=jdbc:mysql://localhost:3306/envios_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.user.name=admin
spring.security.user.password=1234

logging.file.name=logs/envio_ms.log
logging.level.root=INFO
logging.level.com.example.envio_ms=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha