spring.application.name=usuarioseguridad_ms
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/usuarios_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.user.name=admin
spring.security.user.password=1234

logging.file.name=logs/usuarioseguridad_ms.log
logging.level.root=INFO
logging.level.com.example.usuarioseguridad_ms=DEBUG
